An error happened during execution:
Traceback (most recent call last):
  File "/tmp/tmpnk32y_qf.py", line 265, in <module>
    main()
  File "/tmp/tmpnk32y_qf.py", line 67, in main
    num = int(d1 + d2)
ValueError: invalid literal for int() with base 10: '?2'
